#! /bin/bash
check-root() {
	if [[ $EUID -eq 0 ]]
	then 
		echo "This script allows you to create a user on this account"	
	else
		echo "Must be root to add user's to the system"
	exit 1
	fi	
}

create-account() {

	read -p "Enter your username: " username
        echo "You entered $username"
	read -p "Please enter a password: " password

        if egrep "^$username" /etc/passwd
        then
                echo "Oops! This username already has an account."
		
        else
                echo "Creating account with username $username"
        	useradd -m -p "$password" "$username"
        	echo "$username has been added to the system!"
		

        fi

echo "Sending account info to newuser-account.txt"
echo -e "Username: $username \nPassword: $password" > newuser-account.txt
}

change-group() {
	if egrep "^org" /etc/group >> /dev/null
	then
		echo "Adding user to group: org"
	else
		echo "Creating group org and adding new user"
		groupadd org
		
	fi

usermod -a -G org $username
chgrp -R org /home/$username
chmod g+s /home/$username
}
#found this link helpful:
#https://www.cyberciti.biz/tips/howto-write-shell-script-to-add-user.html

check-root
create-account
change-group
